[package]
name = "luban"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
luban-cli = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "luban"
path = "src/main.rs"
