[package]
name = "taiyi-prover"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
bincode = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

clap = { workspace = true }
eth-trie-proofs = { workspace = true }
eyre = { workspace = true }
futures-util = { workspace = true }
redb = { workspace = true }
reqwest = { workspace = true }
reqwest-eventsource = "0.6"
serde_json = { workspace = true }
sp1-sdk = { workspace = true }
taiyi-primitives = { workspace = true }
taiyi-zkvm-types = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }

[[bin]]
name = "taiyi-prover"
path = "src/main.rs"
