name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.

    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any steps you think might be relevant to reproduce the bug.
      placeholder: |
        Steps to reproduce:

        1. Start '...'
        2. Then '...'
        3. Check '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: logs
      description: |
        If applicable, please provide the logs leading up to the bug.

        **Please also provide debug logs.** 
      render: text
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform(s)
      description: What platform(s) did this occur on?
      multiple: true
      options:
        - Linux (x86)
        - Linux (ARM)
        - Mac (Intel)
        - Mac (Apple Silicon)
        - Windows (x86)
        - Windows (ARM)
    validations:
      required: true
  - type: textarea
    id: client-version
    attributes:
      label: What version/commit are you on?
      description: commit hash`
    validations:
      required: true
  - type: textarea
    id: network
    attributes:
      label: Which chain / network are you on?
      description: Valid options are `mainnet`, `holesky`, `helder`, custom network
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/lu-bann/taiyi/blob/main/CONTRIBUTING.md#code-of-conduct)
      options:
        - label: I agree to follow the Code of Conduct
          required: true