[package]
name = "taiyi-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
taiyi-cmd = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tree_hash = { workspace = true }

[dev-dependencies]
