[package]
name = "taiyi"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
taiyi-cli = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "taiyi"
path = "src/main.rs"
